import type { Metadata } from "next";
import { Roboto_Condensed, Inter } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Home/Navbar/ResponsiveNav";

// Roboto Condensed for headings
const robotoCondensed = Roboto_Condensed({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

// Inter for subheadings/body
const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${robotoCondensed.variable} ${inter.variable}`}>
      <body className="font-roboto antialiased">
        <ResponsiveNav />
        {children}
      </body>
    </html>
  );
}
